# Generated by Django 2.2.6 on 2019-11-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VentasTopanzi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
