# Generated by Django 2.2.6 on 2019-12-03 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VentasTopanzi', '0003_remove_contacto_codigocontacto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'permissions': (('admin', 'Es administrador'), ('cliente', 'Es cliente'))},
        ),
    ]
