# Generated by Django 2.2.6 on 2019-11-08 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VentasTopanzi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='codigoContacto',
            field=models.CharField(default=1, max_length=30, verbose_name='Código Contacto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='Teléfono Ej:+56955887741'),
        ),
    ]
