# Generated by Django 2.2.6 on 2019-11-08 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VentasTopanzi', '0002_auto_20191107_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='rut',
            field=models.IntegerField(default=111111111, verbose_name='Rut sin DV: 18224351'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='codigoProducto',
            field=models.CharField(default=1, max_length=30, verbose_name='Código Producto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='codigoVenta',
            field=models.CharField(default=123, max_length=30, verbose_name='Código Producto'),
            preserve_default=False,
        ),
    ]
