# Generated by Django 2.2.6 on 2019-11-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VentasTopanzi', '0003_auto_20191107_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
